[build-system]
  build-backend = "uv_build"
  requires = ["uv_build"]

[project]
  readme = "README.md"
  requires-python = ">= 3.14"
  version = "0.1.0"

[dependency-groups]
  dev = ["dycw-utilities[test]", "rich"]
